version: "0.2"
ignorePaths: [tests/test_jwt.py]
dictionaryDefinitions: []
dictionaries: []
words:
  - jwti
  - railguard
ignoreWords:
  - pyjwt
  - typer
  - pyinstaller
  - pyright
  - pytest
  - setuptools
  - pythonpath
  - venv
import: []
